# Generated by Django 3.2.4 on 2021-06-06 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=122)),
                ('FullName', models.CharField(max_length=122)),
                ('ValueableSuggestion', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
