# Generated by Django 3.2.4 on 2021-06-06 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suggestion',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='suggestion',
            old_name='FullName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='suggestion',
            old_name='ValueableSuggestion',
            new_name='vsug',
        ),
    ]
