# Generated by Django 3.2.4 on 2021-06-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_thoughts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regngo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('password', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('city', models.CharField(max_length=122)),
                ('state', models.CharField(max_length=122)),
                ('pincode', models.IntegerField()),
                ('address', models.TextField()),
                ('number', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
