# Generated by Django 3.2.4 on 2021-06-07 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_regngo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regngo',
            old_name='password',
            new_name='pocname',
        ),
    ]
